---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus.default.svc.cluster.local

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 60
        options:
          path: /etc/grafana/dashboards
          foldersFromFilesStructure: true
      {{ if .Values.dashboards.enable }}
      - name: custom_dashboards
        type: file
        updateIntervalSeconds: 60
        options:
          path: /etc/grafana/custom_dashboards
          foldersFromFilesStructure: true
      {{- end}}