---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  grafana.ini: |
    instance_name = default
    [server]
    domain = grafana-{{ $.Values.deviceId }}-{{ $.Values.teamspace }}.{{ $.Values.domain }}
    root_url = %(protocol)s://%(domain)s/default/
    serve_from_sub_path = true
    router_logging = true
    [dataproxy]
    logging = true
    [security]
    disable_initial_admin_creation = true
    disable_brute_force_login_protection = true
    cookie_secure = true
    allow_embedding = true
    [users]
    default_theme = dark
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    [auth.anonymous]
    enabled = true
    org_role = Editor
    hide_version = true
    [analytics]
    check_for_updates = false
    reporting_enabled = false
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    level = debug
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

